### ISSUE TITLE
Need access to use the On-Demand Infrastructure

### ISSUE THREAD

**Issue by venkatesh-phenompeople** [cdfoundation/cluster#4]
Wanted to figure out spinnaker for continuous deployment for my usecase.

**Comment by danlopez00** [comment]
Hi @venkatesh-phenompeople 
Can you please provide a details of the following

-  use case
- where the open source code repository will be located
- how the community will benefit

**Comment by tracymiranda** [comment]
Closing as there was no follow up, please reopen as needed with info on usecase, benefits and where repo is to be located
